# Generated by Django 4.2.11 on 2025-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogview',
            name='user',
        ),
        migrations.AddField(
            model_name='blogview',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
