# Generated by Django 4.2.11 on 2025-02-07 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_blogview_user_blogview_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogview',
            name='view_count',
        ),
        migrations.AddField(
            model_name='blogview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
