# Generated by Django 4.2.11 on 2025-02-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogview_view_count_blogview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogupload',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
