# Generated by Django 4.2.11 on 2025-01-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='draft',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
