# Generated by Django 4.2.11 on 2025-01-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
