# Generated by Django 4.2.11 on 2024-12-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorStock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stocks.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputedSectorData',
            fields=[
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='computed_data', serialize=False, to='stocks.sector')),
                ('avg_rs', models.FloatField()),
                ('avg_rsi', models.FloatField()),
                ('avg_ema10', models.FloatField()),
                ('avg_ema20', models.FloatField()),
                ('avg_ema30', models.FloatField()),
                ('avg_ema50', models.FloatField()),
                ('avg_ema100', models.FloatField()),
                ('avg_ema200', models.FloatField()),
                ('volume_trend', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComputedStockData',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='computed_data', serialize=False, to='stocks.stock')),
                ('rs', models.FloatField()),
                ('rsi', models.FloatField()),
                ('ema10', models.FloatField()),
                ('ema20', models.FloatField()),
                ('ema30', models.FloatField()),
                ('ema50', models.FloatField()),
                ('ema100', models.FloatField()),
                ('ema200', models.FloatField()),
                ('volume20', models.CharField(max_length=255)),
                ('volume50', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStockData',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='financial_data', serialize=False, to='stocks.stock')),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('open', models.FloatField()),
                ('volume', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorFinancialData',
            fields=[
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='financial_data', serialize=False, to='stocks.sector')),
                ('avg_high', models.FloatField()),
                ('avg_low', models.FloatField()),
                ('avg_close', models.FloatField()),
                ('avg_open', models.FloatField()),
                ('total_volume', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CStockData',
        ),
        migrations.DeleteModel(
            name='FStockData',
        ),
        migrations.AddField(
            model_name='sectorstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='stocks.stock'),
        ),
    ]
