# Generated by Django 4.2.11 on 2024-12-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_sector_sectorstock_stock_computedsectordata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
