# Generated by Django 4.2.11 on 2024-12-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_sectors_delete_sectorstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sectors',
            field=models.ManyToManyField(blank=True, null=True, related_name='stocks', to='stocks.sector'),
        ),
    ]
