# Generated by Django 4.2.11 on 2024-12-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_stock_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstockdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='stocks.sector'),
        ),
    ]
