# Generated by Django 4.2.11 on 2024-12-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_financialstockdata_date_alter_stock_sectors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialStockData',
        ),
    ]
