# Generated by Django 4.2.11 on 2024-12-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_delete_financialstockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('open', models.FloatField()),
                ('volume', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='stocks.stock')),
            ],
        ),
    ]
