# Generated by Django 4.2.11 on 2024-12-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_financialstockdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputedStockData',
        ),
    ]
