# Generated by Django 4.2.11 on 2024-12-31 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_delete_computedstockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs', models.FloatField()),
                ('rsi', models.FloatField()),
                ('ema10', models.FloatField()),
                ('ema20', models.FloatField()),
                ('ema30', models.FloatField()),
                ('ema50', models.FloatField()),
                ('ema100', models.FloatField()),
                ('ema200', models.FloatField()),
                ('volume20', models.CharField(max_length=255)),
                ('volume50', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computed_data', to='stocks.stock')),
            ],
        ),
    ]
