# Generated by Django 4.2.11 on 2024-12-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_computedstockdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedstockdata',
            name='rs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
