# Generated by Django 4.2.11 on 2024-12-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_computedstockdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedstockdata',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computedstockdata',
            name='volume20',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='computedstockdata',
            name='volume50',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
