# Generated by Django 4.2.11 on 2025-01-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_computedstockdata_rsi_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialstockdata',
            index=models.Index(fields=['date'], name='stocks_fina_date_b7c2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstockdata',
            index=models.Index(fields=['stock'], name='stocks_fina_stock_i_bfece6_idx'),
        ),
    ]
