# Generated by Django 4.2.11 on 2025-01-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_financialstockdata_stocks_fina_date_b7c2c1_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financialstockdata',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_date'),
        ),
    ]
