# Generated by Django 4.2.11 on 2025-01-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_financialstockdata_unique_stock_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='computedstockdata',
            index=models.Index(fields=['date'], name='stocks_comp_date_e092a9_idx'),
        ),
        migrations.AddIndex(
            model_name='computedstockdata',
            index=models.Index(fields=['stock'], name='stocks_comp_stock_i_cee056_idx'),
        ),
        migrations.AddConstraint(
            model_name='computedstockdata',
            constraint=models.UniqueConstraint(fields=('stock', 'date'), name='unique_stockIndicator_date'),
        ),
    ]
