# Generated by Django 4.2.11 on 2025-01-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_computedstockdata_stocks_comp_date_e092a9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevVolumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('volume20', models.CharField(blank=True, max_length=255, null=True)),
                ('volume50', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_volumes', to='stocks.stock')),
            ],
        ),
    ]
