# Generated by Django 4.2.11 on 2025-01-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_prevvolumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevVolumesSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('volume20', models.CharField(blank=True, max_length=255, null=True)),
                ('volume50', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_volumes_sector', to='stocks.sector')),
            ],
        ),
    ]
