# Generated by Django 4.2.11 on 2025-01-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_prevvolumessector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorfinancialdata',
            old_name='avg_close',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='sectorfinancialdata',
            old_name='avg_high',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='sectorfinancialdata',
            old_name='avg_low',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='sectorfinancialdata',
            old_name='avg_open',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='sectorfinancialdata',
            old_name='total_volume',
            new_name='volume',
        ),
    ]
