# Generated by Django 4.2.11 on 2025-01-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_rename_avg_close_sectorfinancialdata_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorfinancialdata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
