# Generated by Django 4.2.11 on 2025-01-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_sectorfinancialdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorfinancialdata',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='financial_data_sector', serialize=False, to='stocks.sector'),
        ),
    ]
