# Generated by Django 4.2.11 on 2025-01-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_alter_sectorfinancialdata_sector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectorFinancialData',
        ),
    ]
