# Generated by Django 4.2.11 on 2025-01-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_sectorfinancialdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computedsectordata',
            name='volume_trend',
        ),
        migrations.RemoveField(
            model_name='sectorfinancialdata',
            name='volume',
        ),
        migrations.DeleteModel(
            name='PrevVolumesSector',
        ),
    ]
