# Generated by Django 4.2.11 on 2025-01-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_remove_computedsectordata_volume_trend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computedsectordata',
            old_name='avg_ema10',
            new_name='ema10',
        ),
        migrations.RenameField(
            model_name='computedsectordata',
            old_name='avg_ema100',
            new_name='ema100',
        ),
        migrations.RenameField(
            model_name='computedsectordata',
            old_name='avg_ema20',
            new_name='ema20',
        ),
        migrations.RenameField(
            model_name='computedsectordata',
            old_name='avg_ema200',
            new_name='ema200',
        ),
        migrations.RenameField(
            model_name='computedsectordata',
            old_name='avg_ema30',
            new_name='ema30',
        ),
        migrations.RenameField(
            model_name='computedsectordata',
            old_name='avg_ema50',
            new_name='ema50',
        ),
        migrations.RenameField(
            model_name='computedsectordata',
            old_name='avg_rs',
            new_name='rs',
        ),
        migrations.RenameField(
            model_name='computedsectordata',
            old_name='avg_rsi',
            new_name='rsi',
        ),
        migrations.AddField(
            model_name='computedsectordata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
