# Generated by Django 4.2.11 on 2025-01-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0026_rename_avg_ema10_computedsectordata_ema10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputedSectorData',
        ),
    ]
