# Generated by Django 4.2.11 on 2025-01-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_delete_computedsectordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedSectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('rs', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('ema10', models.FloatField()),
                ('ema20', models.FloatField()),
                ('ema30', models.FloatField()),
                ('ema50', models.FloatField()),
                ('ema100', models.FloatField()),
                ('ema200', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computed_sector_data', to='stocks.sector')),
            ],
        ),
    ]
