# Generated by Django 4.2.11 on 2025-01-10 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0028_computedsectordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sectors', models.ManyToManyField(blank=True, related_name='watchlist_sectors', to='stocks.sector')),
                ('stocks', models.ManyToManyField(blank=True, related_name='watchlist_stocks', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
