# Generated by Django 4.2.11 on 2025-01-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_alter_watchlist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'Watchlist', 'verbose_name_plural': 'Watchlists'},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
