# Generated by Django 4.2.11 on 2025-01-19 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0034_sellstocks_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='sectorIndicatorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('ema10Count', models.IntegerField()),
                ('ema20Count', models.IntegerField()),
                ('ema30Count', models.IntegerField()),
                ('ema50Count', models.IntegerField()),
                ('ema100Count', models.IntegerField()),
                ('ema200Count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_indicator_counts', to='stocks.sector')),
            ],
        ),
    ]
