# Generated by Django 4.2.11 on 2025-01-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0035_sectorindicatorcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultEma', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersetting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
